import express from "express";
const app = express();
const cookieParser = require("cookie-parser");
const dotenv = require("dotenv");
dotenv.config({ path: "src/config/config.env" });
import errorMiddleware from "./middlewares/errors";
import cors from "cors";
import Database from "./db.js";
import auth from "./routes/auth";
import products from "./routes/product";
import reservation from "./routes/reservation";
app.use(cors());
app.use(express.json());
app.use(cookieParser());
app.use("/api/v1", auth);
app.use("/api/v1", products);
app.use("/api/v1", reservation);
app.use(errorMiddleware);
Database();
app.listen(8000, () => console.log("server is up and running"));
